# Section A: Data Structures & Control Structures

### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
list = [1,2,3,4,5]
print(list)

[1, 2, 3, 4, 5]

In [3]:
list.append(6)
print(list)

[1, 2, 3, 4, 5, 6]

In [4]:
list.extend([7,8,9])
print(list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
list.insert(7,4)
print(list)

[1, 2, 3, 4, 5, 6, 7, 4, 8, 9]

In [9]:
list.remove(4)
print(list)

[1, 2, 3, 5, 6, 7, 4, 8, 9]

In [11]:
list.pop(7)
print(list)

[1, 2, 3, 5, 6, 7, 4]

In [12]:
list.index(6)

4

In [13]:
list.count(4)

1

In [14]:
list.sort()
print(list)

[1, 2, 3, 4, 5, 6, 7]

In [15]:
list.sort(reverse = True)
print(list)

[7, 6, 5, 4, 3, 2, 1]

In [16]:
list.clear()
print(list)

[]

### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [17]:
student_name = ("snehdeep","aashu","priyanshi")
print(student_name)

('snehdeep', 'aashu', 'priyanshi')

#### Why does this happen?
#### A tuple is immutable
#### Immutable means you cannot change, add, or remove elements after creation
#### Once a tuple is created, its values are fixed forever

### 3.	Create a set of integers with some duplicate values. Print the set and explain the output

In [19]:
numb = {1, 2, 3, 4, 2, 3, 5}
print(numb)

{1, 2, 3, 4, 5}

In [20]:
type(numb)

set

#### Explanation

#### A set stores only unique values.

#### When you create a set with duplicate numbers (1, 2, 3 appear more than once), Python automatically removes duplicates.

#### The final set contains each number only once.

### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [21]:
dict = {
    "name": "Sneh",
    "age": 22,
    "city": "Indore"
}

# Update age
dict["age"] = 23

# Add new key
dict["email"] = "snehdeepsinghpanwar@example.com"

# Print final dictionary
print(dict)

{'name': 'Sneh', 'age': 23, 'city': 'Indore', 'email': 'snehdeepsinghpanwar@example.com'}

### 5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [23]:
# change age to test different cases
age = int(input("Enter the number :"))

if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")

Enter the number : 23

You are eligible to vote.

### 6.	Given a 'marks' variable, print the grade:
### - 90 and above: 'A'
### - 75–89: 'B'
### - 50–74: 'C'
### - Below 50: 'Fail'

In [2]:
# change marks to test
marks = int(input("enter the marks:"))

if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")

enter the marks: 99

Grade: A

### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [4]:
num = int(input("enter the number"))

if num > 0:
    print("The number is positive.")
    if num % 2 == 0:
        print("It is also even.")
    else:
        print("It is odd.")
        
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

enter the number -9

The number is negative.

# Section B: Numpy

### 8.	Create:
### - A 1D array with values 1 to 5
### - A 2D array (2x3) with values from 10 to 60 in steps of 10

In [83]:
import numpy as np

# (a) Scalar using np.array(5)
scalar = np.array(5)
print("Scalar:")
print(scalar)

# (b) 1D array with values 1 to 5
arr_1d = np.array([1, 2, 3, 4, 5])
print("\n1D Array:")
print(arr_1d)

# (c) 2D array (2x3) with values from 10 to 60 in steps of 10
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60]])
print("\n2D Array (2x3):")
print(arr_2d)

Scalar:
5

1D Array:
[1 2 3 4 5]

2D Array (2x3):
[[10 20 30]
 [40 50 60]]

### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint()

In [84]:
# Random integers between 0 and 100
random_array = np.random.randint(0, 101, size=(4, 4))

print("\n4x4 Random Array:")
print(random_array)

4x4 Random Array:
[[21 74 24 18]
 [90 80 13 42]
 [52 58 77 22]
 [79 37 10 71]]

### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [85]:
import pandas as pd

# Create 3x3 numpy array
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Convert to DataFrame
df = pd.DataFrame(data, columns=['A', 'B', 'C'])

print("\nDataFrame:")
print(df)

DataFrame:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

# Section C: Exploring Pandas

### 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
### - Use .info(), .describe()
### - Select 'Name' and 'City' columns
### - Drop 'City' column
### - Fill any missing values in 'Salary' column with the mean
### - Remove any duplicate rows

In [58]:
import pandas as pd
import numpy as np

In [71]:
data = {
        'Name'   : ['Snehdeep','Priyanshi','Aashu','Senhdeep','Senhyansh','Snehyanshii','Manas','Jay','Aakash','Rohit'],
        'Age'    : [23,22,24,23,23,28,25,27,28,29],
        'City'   : ['Bengaluru', 'Gwalior', 'Mumbai','Bengaluru', 'Chennai','Bhopal', 'Kolkata', 'Jaipur', 'Delhi', 'Pune'],
        'Salary' : [500000, 60000, np.nan, 500000, 70000, 40000, 65000, np.nan, 72000, 58000]
}
df = pd.DataFrame(data)
df

          Name  Age       City    Salary
0     Snehdeep   23  Bengaluru  500000.0
1    Priyanshi   22    Gwalior   60000.0
2        Aashu   24     Mumbai       NaN
3     Senhdeep   23  Bengaluru  500000.0
4    Senhyansh   23    Chennai   70000.0
5  Snehyanshii   28     Bhopal   40000.0
6        Manas   25    Kolkata   65000.0
7          Jay   27     Jaipur       NaN
8       Aakash   28      Delhi   72000.0
9        Rohit   29       Pune   58000.0

### - 1 Use .info(), .describe()

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [73]:
df.describe()

             Age         Salary
count  10.000000       8.000000
mean   25.200000  170625.000000
std     2.573368  203529.525763
min    22.000000   40000.000000
25%    23.000000   59500.000000
50%    24.500000   67500.000000
75%    27.750000  179000.000000
max    29.000000  500000.000000

### -2 Select 'Name' and 'City' columns

In [66]:
df.loc[:,['Name','City']]

          Name       City
0     Snehdeep  Bengaluru
1    Priyanshi    Gwalior
2        Aashu     Mumbai
3     Senhdeep  Bengaluru
4    Senhyansh    Chennai
5  Snehyanshii     Bhopal
6        Manas    Kolkata
7          Jay     Jaipur
8       Aakash      Delhi
9        Rohit       Pune

In [74]:
df_dropped = df.drop('City',axis = 1)
df_dropped

          Name  Age    Salary
0     Snehdeep   23  500000.0
1    Priyanshi   22   60000.0
2        Aashu   24       NaN
3     Senhdeep   23  500000.0
4    Senhyansh   23   70000.0
5  Snehyanshii   28   40000.0
6        Manas   25   65000.0
7          Jay   27       NaN
8       Aakash   28   72000.0
9        Rohit   29   58000.0

### - Fill any missing values in 'Salary' column with the mean

In [75]:
mean_salary = df['Salary'].mean()
mean_salary

np.float64(170625.0)

In [76]:
df['Salary'] = df['Salary'].fillna(mean_salary)

In [77]:
df

          Name  Age       City    Salary
0     Snehdeep   23  Bengaluru  500000.0
1    Priyanshi   22    Gwalior   60000.0
2        Aashu   24     Mumbai  170625.0
3     Senhdeep   23  Bengaluru  500000.0
4    Senhyansh   23    Chennai   70000.0
5  Snehyanshii   28     Bhopal   40000.0
6        Manas   25    Kolkata   65000.0
7          Jay   27     Jaipur  170625.0
8       Aakash   28      Delhi   72000.0
9        Rohit   29       Pune   58000.0

### - Remove any duplicate rows

In [82]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [80]:
df.drop_duplicates()

          Name  Age       City    Salary
0     Snehdeep   23  Bengaluru  500000.0
1    Priyanshi   22    Gwalior   60000.0
2        Aashu   24     Mumbai  170625.0
3     Senhdeep   23  Bengaluru  500000.0
4    Senhyansh   23    Chennai   70000.0
5  Snehyanshii   28     Bhopal   40000.0
6        Manas   25    Kolkata   65000.0
7          Jay   27     Jaipur  170625.0
8       Aakash   28      Delhi   72000.0
9        Rohit   29       Pune   58000.0

In [81]:
df

          Name  Age       City    Salary
0     Snehdeep   23  Bengaluru  500000.0
1    Priyanshi   22    Gwalior   60000.0
2        Aashu   24     Mumbai  170625.0
3     Senhdeep   23  Bengaluru  500000.0
4    Senhyansh   23    Chennai   70000.0
5  Snehyanshii   28     Bhopal   40000.0
6        Manas   25    Kolkata   65000.0
7          Jay   27     Jaipur  170625.0
8       Aakash   28      Delhi   72000.0
9        Rohit   29       Pune   58000.0